/**
 * Diccionario de nombres y apellidos guatemaltecos con tildes y ortografía correcta.
 * Incluye nombres de pila, apellidos hispanos frecuentes y apellidos mayas / ixiles / quichés.
 */

export const NOMBRES_Y_APELLIDOS_GUATEMALA: string[] = [
  // --- Nombres de pila comunes (con tilde y sin tilde) ---
  "Tomás",
  "María",
  "José",
  "Jesús",
  "Ángel",
  "Víctor",
  "Héctor",
  "César",
  "Óscar",
  "Raúl",
  "Rubén",
  "René",
  "Andrés",
  "Félix",
  "Iván",
  "Martín",
  "Agustín",
  "Germán",
  "Hernán",
  "Damián",
  "Julián",
  "Fabián",
  "Adrián",
  "Cristóbal",
  "Moisés",
  "Elías",
  "Isaías",
  "Jonás",
  "Matías",
  "Nicolás",
  "Josué",
  "Noé",
  "Saúl",
  "Bernabé",
  "Bartolomé",
  "Sebastián",
  "Efraín",
  "Ramón",
  "Simón",
  "Joaquín",
  "Lucía",
  "Sofía",
  "Verónica",
  "Débora",
  "Noemí",
  "Inés",
  "Belén",
  "Rocío",
  "Ángela",
  "Mónica",
  "Patricia",
  "Gloria",
  "Silvia",
  "Claudia",
  "Sandra",
  "Blanca",
  "Irma",
  "Vilma",
  "Flor",
  "Dora",
  "Norma",
  "Aura",
  "Marina",
  "Ofelia",
  "Reyna",
  "Leticia",
  "Yolanda",
  "Alicia",
  "Beatriz",
  "Cecilia",
  "Daniela",
  "Gabriela",
  "Andrea",
  "Alejandra",
  "Paola",
  "Laura",
  "Diana",
  "Lorena",
  "Jessica",
  "Brenda",
  "Wendy",
  "Karla",
  "Evelyn",
  "Mayra",
  "Gladis",
  "Miriam",
  "Olga",
  "Raquel",
  "Sara",
  "Ruth",
  "Ester",
  "Rebeca",
  "Abigail",
  "Pedro",
  "Juan",
  "Carlos",
  "Francisco",
  "Antonio",
  "Miguel",
  "Manuel",
  "Domingo",
  "Diego",
  "Lorenzo",
  "Gaspar",
  "Pascual",
  "Mateo",
  "Lucas",
  "Marcos",
  "Pablo",
  "Esteban",
  "Dionicio",
  "Romualdo",
  "Roberto",
  "Luis",
  "Jorge",
  "Mario",
  "Fernando",
  "Eduardo",
  "Ricardo",
  "Alberto",
  "Alejandro",
  "Rodrigo",
  "Rafael",
  "Gabriel",
  "Daniel",
  "Samuel",
  "David",
  "Felipe",
  "Baltazar",
  "Melchor",
  "Gilberto",
  "Adolfo",
  "Gonzalo",
  "Rogelio",
  "Rolando",
  "Salvador",
  "Humberto",
  "Julio",
  "Gustavo",
  "Alfonso",
  "Rodolfo",
  "Guillermo",
  "Enrique",
  "Cristina",
  "Elizabeth",
  "Francisca",
  "Elena",
  "Carmen",
  "Isabel",
  "Juana",
  "Catarina",
  "Rosa",
  "Marta",
  "Jacinta",
  "Manuela",
  "Ana",
  "Teresa",
  "Magdalena",
  "Petronila",
  "Margarita",
  "Esperanza",
  "Petrona",
  "Gricelda",

  // --- Apellidos con tilde esenciales ---
  "Sánchez",
  "Pérez",
  "Gómez",
  "González",
  "López",
  "Martínez",
  "Rodríguez",
  "Hernández",
  "Fernández",
  "Díaz",
  "García",
  "Ramírez",
  "Chávez",
  "Vásquez",
  "Velásquez",
  "Guzmán",
  "Álvarez",
  "Jiménez",
  "Gutiérrez",
  "Núñez",
  "Méndez",
  "Cortés",
  "Muñoz",
  "Ávila",
  "Juárez",
  "León",
  "Benítez",
  "Bermúdez",
  "Cáceres",
  "Godínez",
  "Ordóñez",
  "Marroquín",
  "Girón",
  "Chacón",
  "Chajón",
  "Páez",
  "Márquez",
  "Domínguez",
  "Estévez",
  "Valdés",
  "Suárez",
  "Mendoza",

  // --- Apellidos guatemaltecos tradicionales y locales (Chajul / Ixil / Quiché) ---
  "Asicona",
  "Caba",
  "Laynez",
  "Rivera",
  "Raymundo",
  "Canay",
  "Batz",
  "Hu",
  "Mo",
  "Ijom",
  "Beca",
  "Anay",
  "Lux",
  "Tum",
  "Caal",
  "Solano",
  "Xinic",
  "Chivaz",
  "Nunal",
  "Cobo",
  "Cedillo",
  "Chel",
  "Matom",
  "Us",
  "Sam",
  "Ceto",
  "Brito",
  "Terraza",
  "Bernal",
  "Cobón",
  "Choc",
  "Pop",
  "Tiul",
  "Xol",
  "Cuc",
  "Tut",
  "Chen",
  "Ba",
  "Ical",
  "Pacay",
  "Cuz",
  "Chub",
  "Castillo",
  "Romero",
  "Navarro",
  "Ramos",
  "Gil",
  "Serrano",
  "Blanco",
  "Molina",
  "Morales",
  "Ortega",
  "Delgado",
  "Castro",
  "Ortiz",
  "Estrada",
  "Cabrera",
  "Cifuentes",
  "Palacios",
  "Orellana",
  "Samayoa",
  "Monroy",
  "Solares",
  "Escobar",
  "Cordero",
  "Pineda",
  "Carrillo",
  "Calderón",
  "Barillas",
  "Monterroso",
  "Valladares",
  "Villagrán",
  "Chinchilla",
  "Salguero",
  "Maldonado",
  "Paredes",
  "Rosales",
  "Fuentes",
  "Arriola",
  "Lemus",
  "Galindo",
  "Cruz",
  "Flores",
  "Reyes",
  "Ruiz",
  "Torres",
  "Pacheco",
  "Santiago",
  "Aguilar",
];

// Remover duplicados manteniendo orden
export const DICCIONARIO_NOMBRES = Array.from(new Set(NOMBRES_Y_APELLIDOS_GUATEMALA));

/**
 * Conectores y partículas que NUNCA deben autocompletarse ni reemplazarse por nombres.
 * Permite escribir libremente nombres como "Juan Escobar del Barrio", "Rosa de Canay", etc.
 */
export const PARTICULAS_IGNORADAS = new Set([
  "de",
  "del",
  "la",
  "las",
  "los",
  "y",
  "e",
  "san",
  "santa",
  "el",
  "al",
  "en",
  "da",
  "di",
]);

/**
 * Mapa de palabras sin tilde a su forma ortográfica correcta con tilde.
 * Cuando el usuario escribe la palabra completa y presiona espacio, se acentúa automáticamente.
 */
export const MAPA_CORRECCION_TILDES: Record<string, string> = {
  tomas: "Tomás",
  sanchez: "Sánchez",
  perez: "Pérez",
  gomez: "Gómez",
  gonzalez: "González",
  lopez: "López",
  martinez: "Martínez",
  rodriguez: "Rodríguez",
  hernandez: "Hernández",
  fernandez: "Fernández",
  diaz: "Díaz",
  garcia: "García",
  ramirez: "Ramírez",
  chavez: "Chávez",
  vasquez: "Vásquez",
  velasquez: "Velásquez",
  guzman: "Guzmán",
  alvarez: "Álvarez",
  jimenez: "Jiménez",
  gutierrez: "Gutiérrez",
  nunez: "Núñez",
  mendez: "Méndez",
  cortes: "Cortés",
  munoz: "Muñoz",
  avila: "Ávila",
  juarez: "Juárez",
  leon: "León",
  maria: "María",
  jose: "José",
  jesus: "Jesús",
  angel: "Ángel",
  victor: "Víctor",
  hector: "Héctor",
  cesar: "César",
  oscar: "Óscar",
  raul: "Raúl",
  ruben: "Rubén",
  rene: "René",
  andres: "Andrés",
  felix: "Félix",
  ivan: "Iván",
  martin: "Martín",
  agustin: "Agustín",
  hernan: "Hernán",
  damian: "Damián",
  julian: "Julián",
  fabian: "Fabián",
  adrian: "Adrián",
  cristobal: "Cristóbal",
  moises: "Moisés",
  elias: "Elías",
  isaias: "Isaías",
  jonas: "Jonás",
  matias: "Matías",
  nicolas: "Nicolás",
  josue: "Josué",
  noe: "Noé",
  saul: "Saúl",
  sebastian: "Sebastián",
  efrain: "Efraín",
  ramon: "Ramón",
  simon: "Simón",
  joaquin: "Joaquín",
  lucia: "Lucía",
  sofia: "Sofía",
  veronica: "Verónica",
  debora: "Débora",
  noemi: "Noemí",
  ines: "Inés",
  belen: "Belén",
  rocio: "Rocío",
  marroquin: "Marroquín",
  giron: "Girón",
  chacon: "Chacón",
  chajon: "Chajón",
  dominguez: "Domínguez",
  estevez: "Estévez",
  valdes: "Valdés",
  suarez: "Suárez",
};

/**
 * Normaliza una cadena eliminando tildes y caracteres diacríticos para búsqueda rápida.
 */
export function normalizarParaBusqueda(texto: string): string {
  return texto
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase();
}

/**
 * Si la palabra ingresada corresponde a un nombre que lleva tilde,
 * retorna la versión acentuada correcta.
 */
export function corregirTildeExacta(palabra: string): string | null {
  const norm = normalizarParaBusqueda(palabra.trim());
  if (PARTICULAS_IGNORADAS.has(norm)) return null;
  return MAPA_CORRECCION_TILDES[norm] || null;
}

/**
 * Busca palabras que coincidan con el prefijo ingresado por el usuario.
 * Excluye partículas como "de", "del", "la", "san", etc.
 */
export function buscarSugerenciasNombre(prefijo: string, limite = 3): string[] {
  if (!prefijo || prefijo.trim().length === 0) return [];
  const query = normalizarParaBusqueda(prefijo.trim());

  // Si es un conector común (de, del, la), no sugerir para no interrumpir
  if (PARTICULAS_IGNORADAS.has(query)) return [];

  // Palabras que empiezan con el prefijo normalizado
  const coincidencias = DICCIONARIO_NOMBRES.filter((palabra) => {
    const normalizada = normalizarParaBusqueda(palabra);
    return normalizada.startsWith(query) && normalizada !== query;
  });

  return coincidencias.slice(0, limite);
}
